travis:
  secure:
    BINSTAR_TOKEN: QqLkaB2hmfSpHLOyFEZNIWMFGQY/ZhLV1EEFDSBh+sJSXG70ANe0JPyqFUKdl6AcdcgWU1j8tUsYS7BTx017xl/+RyVq9JmtspxBNM8z86tiqig0X1kyo/yD3lMluX7JENnHJeUzez9QnHy+3OdL9tyBxwbVjPj5G73sDgKxyRxuM9RDA+WUJBBJO+onewrrfeg772Fdc+EQC4BlmXnvG7tD43/dIQAXcY42ImnNd2EkfnXQrsB8WgCew4Yc8e85MxGAPRNfWN/8nqqyHoLHXjG1SgfE/II0mIi0YfCEevGiRQ/oLGbog1fIxhpz/SBcPDmlL7QMIoqf1vkcaUgcqKmiENsrPS39lFF+ozzNpj9T2muBpkVkww0MmLinQjpueYwFZsISz1wuqluzqeLQ5+mipnFTNVr6SML1m5ZYP/kllbA6NTab+v80X8UjgdIZ1ULzvVklUOeND5bkLt3IoiHkrGhoaFBAQTn0LofnjgvbzCpIgnQZxko+SxVxV5U0o+2FpG3E2t9hp3T5lIS1dIOBHOQabQV5wlePGFMh7zodkusotangY/7mp07J6+cVzrxm5LWgjlvLcgDBHfAwlqzpIo7ISyESnu75wVT4CFdS4OmmY4Gzq9X19sh7Px6QvZy+WgmsvBVK46xpH1tqFvAXlwqSCsqxN2H2f7x3xhw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
